### ISSUE TITLE
Started receiving python 2.7 error in unit test: TypeError: str() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by jmathai** [arsenetar/send2trash#36]
I started to receive an error in the unit tests of a python library which depends on send2trash. When running tests using Python 2.7 I receive the following error.

I've been using a fixed version of `send2trash` (Send2Trash==1.3.0) for a long time so I'm a bit perplexed why this just started showing up.

```
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/send2trash/plat_other.py", line 136, in send2trash

    path = str(path, sys.getfilesystemencoding())

TypeError: str() takes at most 1 argument (2 given)
```

**Comment by arsenetar** [comment]
The code producing this error was changed back in f6f63b1796c94fd5388dda10d17ae500be0e350a which would have appeared in release 1.3.1.  Considering this fixed.
