### ISSUE TITLE
Deleting files on windows is slow

### ISSUE THREAD

**Issue by arsenetar** [arsenetar/send2trash#42]
In certain cases deleting a large number of files in windows is seen as being much slower than through explorer.  I did some investigation on this over at arsenetar/dupeguru/issues/664.  I was curious if the IFileOperation interface would provide a faster means of interacting with the windows API, this was technically correct although not a huge savings.  I did find that by batching delete operations to the API (using IFileOperation) did have pretty significant time savings (around 70-75% less time).  It does appear this can be done with SHFileOperation as well so I might give that a try as well.  

Is supporting a list of files to trash something that makes sense to support?  If a platform driver does not support bulk operations then it could just loop over them instead of truly batching.

**Comment by hsoft** [comment]
Yes, it would be a fine addition to the library.

**Comment by arsenetar** [comment]
Looks like I just need to update the unit test to include a case where multiple files are specified, right now my branch is passing tests (but not testing lists).  I'll get a PR open once I get through that.
