### ISSUE TITLE
Update Tests to validate both Windows versions

### ISSUE THREAD

**Issue by arsenetar** [arsenetar/send2trash#44]
Update the unit testing allow for testing both windows versions.

**Comment by arsenetar** [comment]
@BoboTiG Moved this request here since the PR was merged.

**Comment by arsenetar** [comment]
@BoboTiG Looks like I got this working now, you can take a look at the [feature/#44](/arsenetar/send2trash/tree/feature/%2344) branch to see if that addresses this adequately.

**Comment by BoboTiG** [comment]
I did not test, but itLGTM :+1:
