### ISSUE TITLE
Use enviroment markers for OS-specific optional dependencies

### ISSUE THREAD

**Issue by McSinyx** [arsenetar/send2trash#60]
Hi, I noticed that the newly introduced extras are OS-specific.  I think it would be nicer to add the [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) either along or replacing the extras so that e.g. a GNU/Linux user will not be installing pywin32.  [`platform_system`](https://docs.python.org/3/library/platform.html#platform.system) is the most reliable IMHO.

**Comment by arsenetar** [comment]
This should be addressed by commit https://github.com/arsenetar/send2trash/commit/84c220cbd9bad07b28c3e11d4bd6ac9a245115c8

**Comment by McSinyx** [comment]
Thanks!
