### ISSUE TITLE
ImportError: no module named mac

### ISSUE THREAD

**Issue by larryy** [arsenetar/send2trash#68]
After cloning the directory, entering it, and typing 'pip install .' I got what seemed to be a successful build and install, ending in:

```
Successfully built Send2Trash
Installing collected packages: Send2Trash
Successfully installed Send2Trash-1.8.1b0
```

But when I try to run my Python 2.7 script I get an error message:

```
Traceback (most recent call last):
  File "/Users/larryy/Dropbox/src/file_rename.py", line 8, in <module>
    from send2trash import send2trash
  File "/usr/local/lib/python2.7/site-packages/send2trash/__init__.py", line 12, in <module>
    from .mac import send2trash
ImportError: No module named mac
```

As shown, the line of code in question is a standard import:

```
from send2trash import send2trash
```

This is macOS Monterey 12.4 (latest) and the latest Send2Trash (1.8.1b0). Apologies if I've just done something stupid setting things up.

**Comment by arsenetar** [comment]
Likely an issue related to https://github.com/arsenetar/send2trash/commit/d37197c4f7e3e7fa083930aaac0841d1895db134 although there should not be issues... I recommend trying the `1.8.1b0` tag instead of the `master` branch. to see if that resolves the issue.

**Comment by arsenetar** [comment]
This should be good now, I needed to update the `setup.cfg`.

**Comment by larryy** [comment]
I'm sorry to report that "fix" doesn't help.  I installed the latest stable releases for both Python 3 (3.9.13) and Python 2 (2.7.18), reinstalled send2trash, and am getting the same error.  The only customizable options were certain packages, which were all on by default and I left them on, and the install location, which I left at the default.  I confirmed that Python 2 was updated from 2.7.17 to 2.7.18.  I don't know what version Python 3 was at before this install, but it is now at 3.9.13.

I don't think it's meaningful, but I noticed a complaint from the send2trash install about the target site-packages not being in my PATH, and sure enough I still had an old /System/Library path instead of the current /Library path.  But fixing this seems to have changed nothing except that paths reported in the error message are now the Framework paths rather than the /usr/local/lib paths.  The files being pointed to are the same files, just reachable by these two different paths due to symbolic linking.

Traceback (most recent call last):
  File "/Users/larryy/Dropbox/src/file_rename.py", line 8, in <module>
    from send2trash import send2trash
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/send2trash/__init__.py", line 12, in <module>
    from send2trash.mac import send2trash
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/send2trash/mac/__init__.py", line 20, in <module>
    from send2trash.mac.legacy import send2trash  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/send2trash/mac/legacy.py", line 18, in <module>
    GetMacOSStatusCommentString = Foundation.GetMacOSStatusCommentString
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, GetMacOSStatusCommentString): symbol not found

**Comment by arsenetar** [comment]
Yeah, I don't really have anything else then, installing python 3.9.2 back when I was first troubleshooting the `symbol not found` issue somehow "fixed" the system pythons on my development mac which no longer has this issue to date with any of the three python versions present.  I would encourage using a newer version of python if you can.
